# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  hardware.enableRedistributableFirmware = true;
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "r8169" "nvme" ];
  boot.initrd.kernelModules = [ "r8169" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot = {
    supportedFilesystems.zfs = true;
    loader = {
      grub.enable = false;
      efi = {
        efiSysMountPoint = "/efi/a";
        canTouchEfiVariables = false;
      };
      systemd-boot = {
        enable = true;
        configurationLimit = 10;
      };
    };
  };
  systemd.services.esp-mirror = {
  description = "Mirror ESP to secondary disk for boot redundancy";
  wantedBy = [ "multi-user.target" ];
  after = [ "local-fs.target" ];
  serviceConfig.Type = "oneshot";
  script = "${pkgs.rsync}/bin/rsync -a --delete /efi/a/ /efi/b/";
};

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp97s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp97s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp98s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp98s0f1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
